project:
  type: website
  output-dir: docs

website:
  title: "Emil Kamalov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: Simplex
      dark: Darkly
    css: styles.css
    toc: true

editor: visual

