project:
  type: website
  output-dir: docs

website:
  title: "Emil Kamalov"
  description: "Emil Kamalov: Personal Website"
  search: true
  navbar:
    background: "#fcf9f2"
    foreground: "black"
    #logo: logo_grey.png
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - teaching.qmd
      - academic_activities.qmd
      - CV.qmd

  favicon: logo_flavicon.png

  page-footer:
    background: "#121212"
    left: |
      <br><br>
      <i class="fa-regular fa-copyright"></i> Emil Kamalov, 2023<br>
      All content licensed under
      <i class="fa-brands fa-creative-commons"></i> <i class="fa-brands fa-creative-commons-by"></i> 
      <i class="fa-brands fa-creative-commons-sa"></i> <i class="fa-brands fa-creative-commons-nc"></i> 
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer

    right: |
      ![Logo image](logo_bottom_white.png){width=70px}<br><br>
      Made with [R-Studio](https://posit.co/download/rstudio-desktop/) and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [one](https://ucsb-meds.github.io/creating-quarto-websites/) and [two](https://www.andreashandel.com/)

format:
  html:
    theme:
      light: [matria, styles.scss]
    css: styles.css
    toc: true
    linkcolor: "#000000"
    backgroundcolor: "#fcf9f2"
    fontsize: 12pt
    #mainfont: Roboto 

editor: visual
