project:
  type: website
  output-dir: docs

website:
  title: "Emil Kamalov"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - data_collection.qmd
  favicon: logo_top.png

format:
  html:
    theme:
      light: Simplex
      dark: Darkly
    css: styles.css
    toc: true

editor: visual

